"""employee profile fields and daily team photo

Revision ID: b33f9f088e94
Revises: 3d266f5db8a5
Create Date: 2026-08-04 12:00:07.981618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33f9f088e94'
down_revision: Union[str, None] = '3d266f5db8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_team_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.String(length=255), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=True),
    sa.Column('drive_status', sa.Enum('pending', 'uploaded', 'failed', name='drive_sync_status'), nullable=False),
    sa.Column('drive_error', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day BETWEEN 1 AND 31', name='chk_photo_day'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='chk_photo_month'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'year', 'month', 'day', name='uq_daily_photo_team_day')
    )
    op.add_column('employees', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('blood_type', sa.String(length=10), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'avatar_path')
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'blood_type')
    op.drop_column('employees', 'phone')
    op.drop_table('daily_team_photos')
    # ### end Alembic commands ###
