"""multi-team roster and per-team attendance entries

Revision ID: b9bf00cb9f68
Revises: b33f9f088e94
Create Date: 2026-08-04 15:32:29.604342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bf00cb9f68'
down_revision: Union[str, None] = 'b33f9f088e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - reordered by hand ###
    # 1. Drop the OLD composite FK first — it depends on monthly_roster's old
    #    unique constraint, so that constraint can't be dropped while it exists.
    op.drop_constraint('fk_entry_roster', 'attendance_entries', type_='foreignkey')
    # 2. Now monthly_roster's unique constraint can be swapped.
    op.drop_constraint('uq_roster_employee_month', 'monthly_roster', type_='unique')
    op.create_unique_constraint('uq_roster_employee_team_month', 'monthly_roster', ['employee_id', 'team_id', 'year', 'month'])
    # 3. attendance_entries gets its own team_id + constraints, then the new FK.
    op.add_column('attendance_entries', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_entry_employee_day', 'attendance_entries', type_='unique')
    op.create_unique_constraint('uq_entry_employee_team_day', 'attendance_entries', ['employee_id', 'team_id', 'year', 'month', 'day'])
    op.create_foreign_key(None, 'attendance_entries', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_entry_roster', 'attendance_entries', 'monthly_roster', ['employee_id', 'team_id', 'year', 'month'], ['employee_id', 'team_id', 'year', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_roster_employee_team_month', 'monthly_roster', type_='unique')
    op.create_unique_constraint('uq_roster_employee_month', 'monthly_roster', ['employee_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('fk_entry_roster', 'attendance_entries', type_='foreignkey')
    op.drop_constraint(None, 'attendance_entries', type_='foreignkey')
    op.create_foreign_key('fk_entry_roster', 'attendance_entries', 'monthly_roster', ['employee_id', 'year', 'month'], ['employee_id', 'year', 'month'])
    op.drop_constraint('uq_entry_employee_team_day', 'attendance_entries', type_='unique')
    op.create_unique_constraint('uq_entry_employee_day', 'attendance_entries', ['employee_id', 'year', 'month', 'day'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendance_entries', 'team_id')
    # ### end Alembic commands ###
