"""daily photos allow multiple per day

Revision ID: bfa67264b264
Revises: 7160ac23bcde
Create Date: 2026-08-07 15:31:35.642781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa67264b264'
down_revision: Union[str, None] = '7160ac23bcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_daily_photo_team_day', 'daily_team_photos', type_='unique')
    op.create_index('ix_daily_photo_team_day', 'daily_team_photos', ['team_id', 'year', 'month', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_photo_team_day', table_name='daily_team_photos')
    op.create_unique_constraint('uq_daily_photo_team_day', 'daily_team_photos', ['team_id', 'year', 'month', 'day'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
